<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class Animal extends Model
{
    protected $fillable = [
        'especie_id',
        'actividad_id',
        'name',
        'description',
    ];

    public function especie()
    {
        return $this->belongsTo('App\Models\Especie', 'especie_id');
    }

    public function recintoanimals()
    {
        return $this->hasMany('App\Models\RecintoAnimal', 'animal_id');
    }

    public function cuidadoranimals()
    {
        return $this->hasMany('App\Models\CuidadorAnimal', 'cuidador_id');
    }

    public function actividad()
    {
        return $this->belongsTo('App\Models\Actividad', 'actividad_id');
    }
}
