<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class RecintoAnimal extends Model
{
    protected $fillable = [
        'recinto_id',
        'animal_id',
    ];

    public function recinto()
    {
        return $this->belongsTo('App\Models\Recinto', 'recinto_id');
    }

    public function animal()
    {
        return $this->belongsTo('App\Models\Animal', 'animal_id');
    }
}
